# Generated by Django 4.2.6 on 2023-12-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LearnData', '0001_initial'),
        ('Account', '0002_remove_decan_id_decan_id_faculty_students_num_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_and_traffic', models.TextField()),
                ('id_discip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnData.desciplines')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.students')),
            ],
            options={
                'unique_together': {('id_student', 'id_discip')},
            },
        ),
        migrations.CreateModel(
            name='HomeWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField()),
                ('id_discip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnData.desciplines')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.teachers')),
            ],
            options={
                'unique_together': {('id_teacher', 'id_discip')},
            },
        ),
    ]
