# Generated by Django 4.2.6 on 2023-12-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id_faculty', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_faculty', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id_spec', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_spec', models.TextField()),
                ('id_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubsu.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('num_group', models.TextField(primary_key=True, serialize=False)),
                ('id_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubsu.specials')),
            ],
        ),
        migrations.CreateModel(
            name='Fac_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubsu.faculties')),
            ],
        ),
    ]
