# Generated by Django 4.2.6 on 2023-12-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('kubsu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_teacher',
            name='id_teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Account.teachers'),
        ),
        migrations.AlterUniqueTogether(
            name='fac_teacher',
            unique_together={('id_faculty', 'id_teacher')},
        ),
    ]
