# Generated by Django 4.2.6 on 2023-12-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_students_password_teachers_password'),
        ('kubsu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_descip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubsu.faculties')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.teachers')),
            ],
        ),
    ]
