# Generated by Django 4.2.6 on 2023-12-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnData', '0001_initial'),
        ('kubsu', '0002_teacher_descip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_descip',
            name='id_faculty',
        ),
        migrations.AddField(
            model_name='teacher_descip',
            name='id_discip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LearnData.desciplines'),
        ),
    ]
