# Generated by Django 4.2.6 on 2023-12-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnData', '0001_initial'),
        ('kubsu', '0003_remove_teacher_descip_id_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_descip',
            name='id_discip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnData.desciplines'),
        ),
    ]
