# Generated by Django 4.2.6 on 2023-12-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('kubsu', '0002_fac_teacher_id_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desciplines',
            fields=[
                ('id_discip', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('id_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubsu.specials')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval', models.TextField()),
                ('weekday', models.TextField()),
                ('id_discip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnData.desciplines')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.teachers')),
                ('num_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubsu.groups')),
            ],
            options={
                'unique_together': {('time_interval', 'id_teacher', 'weekday')},
            },
        ),
    ]
