# Generated by Django 4.2.6 on 2023-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('name', models.TextField()),
                ('patronym', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('name', models.TextField()),
                ('patronym', models.TextField()),
                ('academic_title', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
