# Generated by Django 4.2.6 on 2023-12-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kubsu', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('name', models.TextField()),
                ('patronym', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('academic_title', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('name', models.TextField()),
                ('patronym', models.TextField()),
                ('num_group', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='kubsu.groups')),
            ],
        ),
    ]
