# Generated by Django 4.2.6 on 2023-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('name', models.TextField()),
                ('patronym', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('name', models.TextField()),
                ('patronym', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('academic_title', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
