# Generated by Django 4.2.6 on 2023-12-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubsu', '0002_fac_teacher_id_teacher_and_more'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decan',
            fields=[
                ('id_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kubsu.faculties')),
                ('password', models.TextField()),
            ],
        ),
    ]
