# Generated by Django 4.2.6 on 2023-12-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubsu', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decan',
            name='id',
        ),
        migrations.AddField(
            model_name='decan',
            name='id_faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kubsu.faculties'),
        ),
        migrations.AddField(
            model_name='students',
            name='num_group',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='kubsu.groups'),
        ),
    ]
