# Generated by Django 4.2.6 on 2023-12-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_decan_id_decan_id_faculty_students_num_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.TextField(default='password'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.TextField(default='password'),
        ),
    ]
